{% set name = "cppyy-backend" %}
{% set version = "1.14.3" %}
{% set cling_name = "clingwrapper" %}
{% set cling_version = "6.21.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy-backend/cppyy-backend-{{ version }}.tar.gz
  sha256: e60d1b93804ef8056375852babb901532cf340062920c496732aba17102bcd32

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # This is the only package that will ever depend upon cppyy-cling so we pin
    # it exactly. 
    - cppyy-cling {{ cling_version }}
  run:
    - python
    - cppyy-cling {{ cling_version }}

test:
  imports:
    - cppyy_backend

about:
  home: https://pypi.org/project/cppyy-backend/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Automatic Python-C++ bindings
  description: |
    C/C++ wrapper around Cling, the LLVM-based interactive C++ interpreter, for
    use by cppyy, providing stable C and C++ Reflection APIs.
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy-backend/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
