{% set version = "1.15.3" %}

package:
  name: cppyy-backend
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cppyy-backend/cppyy-backend-{{ version }}.tar.gz
  sha256: 4578216c16667f858a3f05bb30baa12d3d8cb8ee365bddd904e25fc2d3488d65
  patches:
    - cflags.patch  # [build_platform != target_platform]

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.30.0
  run:
    - python
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.30.0

test:
  imports:
    - cppyy_backend

about:
  home: https://pypi.org/project/cppyy-backend/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Automatic Python-C++ bindings
  description: |
    C/C++ wrapper around Cling, the LLVM-based interactive C++ interpreter, for
    use by cppyy, providing stable C and C++ Reflection APIs.
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://github.com/wlav/cppyy-backend

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
