{% set name = "cppyy-backend" %}
{% set version = "1.14.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy-backend/cppyy-backend-{{ version }}.tar.gz
  sha256: 51ac01c4cca28ef54544ce0b41355d885242f1a0178619bea071f5c43fd03dac
  patches:
    - cflags.patch  # [build_platform != target_platform]

build:
  number: 2
  skip: true  # [win]
  # cppyy-cling is not cross-compiled for pypy yet
  skip: true  # [build_platform != target_platform and python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.27.1
  run:
    - python
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.27.1

test:
  imports:
    - cppyy_backend

about:
  home: https://pypi.org/project/cppyy-backend/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Automatic Python-C++ bindings
  description: |
    C/C++ wrapper around Cling, the LLVM-based interactive C++ interpreter, for
    use by cppyy, providing stable C and C++ Reflection APIs.
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy-backend/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
