{% set name = "cppyy-backend" %}
{% set version = "1.14.6" %}
{% set cling_version = "6.25.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cppyy-backend/cppyy-backend-{{ version }}.tar.gz
  sha256: 42598fc1f578ccd389a8c5a5410f57809726dce758185585c3a2ab1d72bd4ed3
  patches:
    - cflags.patch  # [build_platform != target_platform]

build:
  number: 0
  skip: true  # [win]
  # cppyy-cling is not cross-compiled for pypy yet
  skip: true  # [build_platform != target_platform and python_impl == "pypy"]
  script: {{ PYTHON }} -m pip install -vv --no-deps .

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    # This is the only package that will ever depend upon cppyy-cling so we pin
    # it exactly. 
    - cppyy-cling {{ cling_version }}
  run:
    - python
    - cppyy-cling {{ cling_version }}

test:
  imports:
    - cppyy_backend

about:
  home: https://pypi.org/project/cppyy-backend/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Automatic Python-C++ bindings
  description: |
    C/C++ wrapper around Cling, the LLVM-based interactive C++ interpreter, for
    use by cppyy, providing stable C and C++ Reflection APIs.
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cppyy-backend/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
