schema_version: 1

context:
  name: cppyy-backend
  version: 1.15.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cppyy-backend/cppyy-backend-${{ version }}.tar.gz
  sha256: 8d0ec169f6ea40d26999a61b274ce2ac880082e8d16aace6a0702933d3d835fc

build:
  number: 5
  skip: win
  script: ${{ PYTHON }} -m pip install -vv --no-deps --no-build-isolation .

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.30.0
  run:
    - python
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.30.0

tests:
  - python:
      imports:
        - cppyy_backend

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Automatic Python-C++ bindings
  description: |
    C/C++ wrapper around Cling, the LLVM-based interactive C++ interpreter, for
    use by cppyy, providing stable C and C++ Reflection APIs.
  homepage: https://pypi.org/project/cppyy-backend/
  repository: https://bitbucket.org/wlav/cppyy-backend/src
  documentation: http://cppyy.readthedocs.io/

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
