travis:
  secure:
    BINSTAR_TOKEN: kJSLjNTJ1nlcIBXzw/MdiJS0oio1z9Dxom1H4Lkt4YSv+NN/3bW4jPAlNf8LBZDSug3MVcJlYxiQvUdRgnYF5Ssv4bEUlDvwTFqvhQr+ZORZD+0nqek4mxc+w6jx9zD/i4d3OEFZ0fbCGBy5vCFqok+bHq8B8yhg+Ik5R8ZvpjlBqa/6mQnbDQtvUKiGdfMHpedMo7JtBnR5BiOqIWwIshjnYDs8RnsHi6WsfvkL4vEG2hEJQj09X7Rt0T+zb0nt4yBH4s2kpDRjF4v81raf9IqNSCHOC9wh7M6c4J2l+RSVthAewsOEYT1a9qogE21pcd0JDSMPpElVruOiyYoLv2XSySrTn0tnCFUi0UPAItVbIZD8Fbn04y+U5LfKRm0bIfeNZYuYyp4BVo40gAeHTC/uxacaBGEu3O0lwURG/PFWB19shmZeUYzSSD2j6hI7vfn2RilpsId50I7G5ji+9sRAD91raVszCwOZvNUYKL0LqDJHDspNF+wZ8EUZrlG8ANFwE3kioBEdtg+1QaOQC7CtJHDhFxBEtz095HrjG5eRVm7Tz0t2Qw4+i7jx5dGtsyEPQGqXb37pxCgf+26+xA6QZANnlQ1cV9l1r9y6/enAVHNjpfoMmK34YJlrUjzzamURTXkWwegtgXMtmTf2ARzhti47E6aBJB2ySimeVjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
